apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotal-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kotalco/community-api:develop
          ports:
            - containerPort: 3000
